ALTER TABLE public.profiles
  ADD COLUMN biological_sex text DEFAULT 'female',
  ADD COLUMN age integer DEFAULT 30,
  ADD COLUMN height_ft integer,
  ADD COLUMN height_in integer,
  ADD COLUMN current_weight_lbs numeric,
  ADD COLUMN goal_weight_lbs numeric,
  ADD COLUMN activity_level text,
  ADD COLUMN bmi numeric,
  ADD COLUMN bmr numeric,
  ADD COLUMN tdee numeric,
  ADD COLUMN selected_goal text,
  ADD COLUMN target_calories integer,
  ADD COLUMN protein_pct integer DEFAULT 30,
  ADD COLUMN carb_pct integer DEFAULT 40,
  ADD COLUMN fat_pct integer DEFAULT 30,
  ADD COLUMN meals_selected text[] DEFAULT '{}',
  ADD COLUMN protein_choice text,
  ADD COLUMN carb_choice text,
  ADD COLUMN veggie_choice text,
  ADD COLUMN fat_choice text,
  ADD COLUMN weekly_budget text,
  ADD COLUMN serving_size text DEFAULT 'just_me',
  ADD COLUMN onboarding_completed boolean DEFAULT false;